---
- name: Install Loki on Ubuntu 
  hosts: all
  become: yes

  tasks:
    - name: Get the latest version tag of Loki from GitHub
      ansible.builtin.shell: |
        curl -s "https://api.github.com/repos/grafana/loki/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+'
      register: loki_version
      changed_when: false

    - name: Set Loki version
      set_fact:
        loki_version: "{{ loki_version.stdout }}"

    - name: Create directory to store Loki binary and configuration file
      ansible.builtin.file:
        path: /opt/loki
        state: directory

    - name: Download Loki archive from releases page
      ansible.builtin.get_url:
        url: "https://github.com/grafana/loki/releases/download/v{{ loki_version }}/loki-linux-amd64.zip"
        dest: /opt/loki/loki.gz

    - name: Extract Loki binary from archive
      ansible.builtin.unarchive:
        src: /opt/loki/loki.gz
        dest: /opt/loki
        remote_src: yes

    - name: Set execute permission for Loki binary
      ansible.builtin.file:
        path: /opt/loki/loki
        mode: '0755'

    - name: Create symbolic link for Loki command
      ansible.builtin.file:
        src: /opt/loki/loki
        dest: /usr/local/bin/loki
        state: link

    - name: Download configuration file for Loki
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/grafana/loki/v{{ loki_version }}/cmd/loki/loki-local-config.yaml"
        dest: /opt/loki/loki-local-config.yaml

    - name: Verify Loki installation
      ansible.builtin.command: loki --version
      register: loki_version_output
      failed_when: loki_version_output.rc != 0

    - name: Create systemd unit file for Loki
      ansible.builtin.copy:
        dest: /etc/systemd/system/loki.service
        content: |
          [Unit]
          Description=Loki log aggregation system
          After=network.target

          [Service]
          ExecStart=/opt/loki/loki -config.file=/opt/loki/loki-local-config.yaml
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to read new unit file
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start Loki service
      ansible.builtin.systemd:
        name: loki
        state: started
        enabled: yes

    - name: Ensure Loki service is running
      ansible.builtin.systemd:
        name: loki
        state: started

